# Generated by Django 3.2.9 on 2021-11-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(max_length=6, unique=True)),
                ('nombre_ciudad', models.CharField(max_length=255)),
            ],
        ),
    ]
