# Generated by Django 3.2.9 on 2021-11-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viveros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='viveros.ciudades')),
            ],
        ),
    ]
