# Generated by Django 3.2.9 on 2021-11-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0002_viveros'),
    ]

    operations = [
        migrations.AddField(
            model_name='viveros',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
